### ISSUE TITLE
Error while installing with recomended setting 

### ISSUE THREAD

**Issue by hrvojej** [strapi/strapi-starter-next-ecommerce#20]
I got following error right after running:

`npx create-strapi-starter projectFolder next-ecommerce
`

```
[develop:frontend] Starting: develop:frontend
[develop:backend ] internal/modules/cjs/loader.js:888
[develop:backend ]   throw err;
[develop:backend ]   ^
[develop:backend ] 
[develop:backend ] Error: Cannot find module '/home/myuser/projectFolder/develop:backend'
[develop:backend ]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
[develop:backend ]     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
[develop:backend ]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[develop:backend ]     at internal/main/run_main_module.js:17:47 {
[develop:backend ]   code: 'MODULE_NOT_FOUND',
[develop:backend ]   requireStack: []
[develop:backend ] }
[develop:frontend] internal/modules/cjs/loader.js:888
[develop:frontend]   throw err;
[develop:frontend]   ^
[develop:frontend] 
[develop:frontend] Error: Cannot find module '/home/myuser/projectFolder/develop:frontend'
[develop:frontend]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
[develop:frontend]     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
[develop:frontend]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[develop:frontend]     at internal/main/run_main_module.js:17:47 {
[develop:frontend]   code: 'MODULE_NOT_FOUND',
[develop:frontend]   requireStack: []
[develop:frontend] }
Done in 0.72s.
```

Before that I've run custom Strapi installation without problem with PostgreSQL database on same server/account.

**Comment by hrvojej** [comment]
Error happened because my web server proxy wasn't configured properly. 
If you ran across this problem than it's important that you configure backend and frontend server block in your web server configuration.  

In my case I was using nginx as web server. Following this answer:
[https://serverfault.com/a/792769/336745](https://serverfault.com/a/792769/336745)

helped me configure it properly.

After that installation with PostgresSQL and my own domain for frontend and subdomain for backend went ok.
